<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#141b2b">
    <title>TechPulse Pakistan</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <div class="announcement">Free nationwide delivery on orders over Rs. 2,999 <span>&middot;</span> Official warranty on every order</div>
    <header class="site-header">
        <div class="page-width header-main">
            <a class="brand" href="{{ route('home') }}"><span class="brand-mark"><span class="material-symbols-outlined">bolt</span></span>TechPulse Pakistan</a>
            <form class="search-box" action="{{ route('shop') }}" method="get"><input type="search" name="q" placeholder="Search headphones, watches, chargers..." aria-label="Search products"><button type="submit">Search</button></form>
            <div class="header-actions"><a href="{{ route('cart') }}">Cart <span data-cart-count hidden>0</span></a></div>
        </div>
        <nav class="page-width main-nav"><a href="{{ route('home') }}">Home</a><a href="{{ route('shop') }}">Shop all</a><a href="{{ route('shop', ['q' => 'audio']) }}">Audio</a><a href="{{ route('shop', ['q' => 'watch']) }}">Smart watches</a><a href="{{ route('shop', ['q' => 'gaming']) }}">Gaming</a><a href="{{ route('shop') }}#deals">Flash deals</a></nav>
    </header>

    @php
        $products = [
            ['id' => 'soundcore-space-one', 'title' => 'Anker Soundcore Space One ANC Headphones', 'brand' => 'ANKER SOUNDCORE', 'category' => 'audio', 'price' => 24999, 'old' => 29999, 'rating' => '4.8', 'reviews' => 124, 'icon' => 'headphones', 'badge' => '17% OFF'],
            ['id' => 'soundpeats-capsule3', 'title' => 'SoundPEATS Capsule3 Pro Wireless Earbuds', 'brand' => 'SOUNDPEATS', 'category' => 'audio', 'price' => 12999, 'old' => 15999, 'rating' => '4.7', 'reviews' => 86, 'icon' => 'earbuds', 'badge' => 'BESTSELLER'],
            ['id' => 'samsung-watch6', 'title' => 'Samsung Galaxy Watch6 Classic 47mm', 'brand' => 'SAMSUNG', 'category' => 'wearables', 'price' => 58999, 'old' => 68999, 'rating' => '4.9', 'reviews' => 72, 'icon' => 'watch', 'badge' => '14% OFF'],
            ['id' => 'razer-deathadder-v3', 'title' => 'Razer DeathAdder V3 Ergonomic Gaming Mouse', 'brand' => 'RAZER', 'category' => 'gaming', 'price' => 18999, 'old' => 24999, 'rating' => '4.8', 'reviews' => 142, 'icon' => 'mouse', 'badge' => '24% OFF'],
            ['id' => 'wireless-earbuds-pro', 'title' => 'Wireless Bluetooth Earbuds Pro ANC', 'brand' => 'TECHPULSE AUDIO', 'category' => 'audio', 'price' => 8999, 'old' => 11999, 'rating' => '4.6', 'reviews' => 58, 'icon' => 'earbuds', 'badge' => '25% OFF'],
        ];
        $categories = [
            ['Audio & Sound', '51 products', 'headphones', 'audio'], ['Mobile accessories', '68 products', 'phone_android', 'mobile'],
            ['Gaming gear', '54 products', 'sports_esports', 'gaming'], ['Smart watches', '37 products', 'watch', 'watch'],
            ['Computer accessories', '29 products', 'keyboard', 'computer'], ['Power & charging', '48 products', 'bolt', 'charger'],
            ['Smart home', '23 products', 'nest_cam_iq_outdoor', 'smart'], ['Tech gadgets', '42 products', 'memory', 'tech'],
        ];
    @endphp

    @if (request()->routeIs('home'))
        <main>
            <section class="page-width hero">
                <div class="hero-copy"><span class="eyebrow"><span class="eyebrow-dot"></span> Pakistan's official tech store</span><h1>Latest tech.<br><span>Zero compromise.</span></h1><p>Discover verified smart gadgets and accessories at honest Pakistani prices. Every order comes with genuine local warranty and delivery across Pakistan.</p><div class="hero-buttons"><a class="button button-primary" href="{{ route('shop') }}">Shop the collection <span class="material-symbols-outlined">arrow_forward</span></a><a class="button button-light" href="#featured">Explore bestsellers</a></div><div class="hero-trust"><span><span class="material-symbols-outlined">verified</span> Official warranty</span><span><span class="material-symbols-outlined">local_shipping</span> Nationwide COD</span><span><span class="material-symbols-outlined">task_alt</span> 100% original</span></div></div>
                <div class="hero-art" aria-label="Soundcore headphones illustration"><div class="hero-disc"></div><div class="hero-device"><span class="material-symbols-outlined">headphones</span></div><div class="floating-spec top"><span class="material-symbols-outlined">graphic_eq</span><span>Adaptive ANC<br><strong>Noise cancelled</strong></span></div><div class="floating-spec bottom"><span class="material-symbols-outlined">battery_charging_full</span><span>Up to <strong>40 hours</strong><br>playtime</span></div></div>
            </section>
            <section class="page-width section"><div class="section-heading"><div><span class="section-kicker">Find your next favorite</span><h2>Shop by category</h2><p>Good gear, sorted by what you need.</p></div><a class="text-link" href="{{ route('shop') }}">Browse all <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="category-grid">@foreach ($categories as $category)<a class="category-tile" href="{{ route('shop', ['q' => $category[3]]) }}"><span class="category-icon"><span class="material-symbols-outlined">{{ $category[2] }}</span></span><span><strong>{{ $category[0] }}</strong><small>{{ $category[1] }}</small></span></a>@endforeach</div></section>
            <section class="page-width feature-strip"><div><span class="category-icon"><span class="material-symbols-outlined">local_shipping</span></span><span><strong>Fast delivery</strong><p>2-4 business days nationwide.</p></span></div><div><span class="category-icon"><span class="material-symbols-outlined">account_balance_wallet</span></span><span><strong>Pay your way</strong><p>COD, Easypaisa and JazzCash.</p></span></div><div><span class="category-icon"><span class="material-symbols-outlined">verified</span></span><span><strong>Genuine gear</strong><p>Official local brand warranty.</p></span></div><div><span class="category-icon"><span class="material-symbols-outlined">support_agent</span></span><span><strong>Real support</strong><p>People ready to help, 7 days.</p></span></div></section>
            <section class="page-width section" id="featured"><div class="section-heading"><div><span class="section-kicker">Customer favorites</span><h2>Featured products</h2><p>Popular picks, checked and ready to ship.</p></div><a class="text-link" href="{{ route('shop') }}">View all products <span class="material-symbols-outlined">arrow_forward</span></a></div><div class="product-grid">@foreach (array_slice($products, 0, 4) as $product) @include('partials.product-card', ['product' => $product]) @endforeach</div></section>
            <section class="page-width section" id="deals"><div class="sale-banner"><div><span class="sale-tag">Limited time flash deals</span><h2>Big tech, better prices.</h2><p>Save on audio, fast chargers and smart wearables. Free delivery on qualifying orders, anywhere in Pakistan.</p></div><a class="button button-danger" href="{{ route('shop') }}">Shop the deals <span class="material-symbols-outlined">arrow_forward</span></a></div></section>
        </main>
    @elseif (request()->routeIs('shop'))
        <main class="page-width shop-layout"><aside class="filter-panel"><h2>Filters</h2><div class="filter-group options-row"><h3>Category</h3><button class="filter-option selected" data-category-filter="all">All products</button><button class="filter-option" data-category-filter="audio">Audio & sound</button><button class="filter-option" data-category-filter="wearables">Wearables</button><button class="filter-option" data-category-filter="gaming">Gaming</button></div><div class="filter-group"><h3>Availability</h3><label class="filter-option"><input type="checkbox" checked data-stock-filter> In stock</label><label class="filter-option"><input type="checkbox" data-sale-filter> On sale</label></div><div class="filter-group"><h3>Price range</h3><label class="filter-option"><input type="radio" name="price" value="all" checked data-price-filter> Any price</label><label class="filter-option"><input type="radio" name="price" value="under-20000" data-price-filter> Under Rs. 20,000</label></div></aside><div><div class="shop-toolbar"><div><h1>Shop all products</h1><p>Verified tech, delivered across Pakistan.</p></div><select class="sort-select" aria-label="Sort products"><option value="featured">Featured</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></div><div class="product-grid shop-grid">@foreach ($products as $product) @include('partials.product-card', ['product' => $product]) @endforeach</div></div></main>
    @elseif (request()->routeIs('product.show'))
        @php($detail = collect($products)->firstWhere('id', request()->route('product')) ?? $products[4])
        <main class="page-width"><div class="breadcrumb"><a href="{{ route('home') }}">Home</a> / <a href="{{ route('shop') }}">Shop</a> / Audio / Wireless earbuds</div><section class="product-detail"><div class="detail-art"><span class="material-symbols-outlined">earbuds</span></div><div class="detail-copy"><span class="section-kicker">{{ $detail['brand'] }}</span><h1>{{ $detail['title'] }}</h1><div class="product-rating"><span class="material-symbols-outlined">star</span><span class="material-symbols-outlined">star</span><span class="material-symbols-outlined">star</span><span class="material-symbols-outlined">star</span><span class="material-symbols-outlined">star_half</span><strong>{{ $detail['rating'] }}</strong><small>({{ $detail['reviews'] }} verified reviews)</small></div><p>Immersive sound without the noise. Enjoy adaptive active noise cancellation, clear calls and all-day comfort, backed by a 12-month local warranty.</p><span class="detail-stock">Lahore warehouse - Ready to ship</span><div class="detail-price"><strong>Rs. {{ number_format($detail['price']) }}</strong><del>Rs. {{ number_format($detail['old']) }}</del><span class="sale-tag">{{ $detail['badge'] }}</span></div><div class="detail-checks"><span><span class="material-symbols-outlined">verified</span> 12-month official warranty</span><span><span class="material-symbols-outlined">local_shipping</span> Free delivery over Rs. 2,999</span><span><span class="material-symbols-outlined">payments</span> Cash on delivery available</span><span><span class="material-symbols-outlined">assignment_return</span> 7-day easy returns</span></div><div class="quantity-control" data-quantity-control><button data-step="-1" aria-label="Decrease quantity">-</button><output>1</output><button data-step="1" aria-label="Increase quantity">+</button></div><div class="buy-row"><button class="button button-primary" data-add-cart data-product-add data-id="{{ $detail['id'] }}" data-title="{{ $detail['title'] }}" data-price="{{ $detail['price'] }}" data-icon="{{ $detail['icon'] }}"><span class="material-symbols-outlined">shopping_bag</span>Add to cart</button><a class="button button-outline" href="{{ route('cart') }}">Buy now</a></div></div></section></main>
    @else
        <main class="page-width"><div class="breadcrumb"><a href="{{ route('home') }}">Home</a> / Shopping cart</div><div class="cart-layout"><section class="cart-panel"><h1>Your cart <small data-cart-summary-count></small></h1><div data-cart-items></div><a class="text-link" href="{{ route('shop') }}"><span class="material-symbols-outlined">arrow_back</span> Continue shopping</a></section><aside class="checkout-panel"><h2>Order summary</h2><div class="summary-row"><span>Subtotal</span><span data-subtotal>Rs. 0</span></div><div class="summary-row"><span>Delivery</span><span data-shipping>Free</span></div><div class="summary-row total"><span>Total</span><span data-total>Rs. 0</span></div><form class="checkout-form" data-checkout-form><label>Full name<input name="name" autocomplete="name" required placeholder="Your name"></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" required pattern="03[0-9]{9}" title="Enter an 11-digit Pakistani mobile number starting with 03" placeholder="03XX XXXXXXX"></label><label>Delivery city<input name="city" required placeholder="e.g. Lahore"></label><label>Payment method<select name="payment"><option>Cash on delivery</option><option>Easypaisa</option><option>JazzCash</option></select></label><button class="button button-dark" type="submit" data-checkout-submit disabled>Place order <span class="material-symbols-outlined">arrow_forward</span></button><div class="notice" data-checkout-notice role="status"></div></form><div class="trust-note"><span class="material-symbols-outlined">lock</span> Your details stay private and secure</div></aside></div></main>
    @endif

    <footer class="site-footer"><div class="page-width footer-grid"><div><a class="brand" href="{{ route('home') }}"><span class="brand-mark"><span class="material-symbols-outlined">bolt</span></span>TechPulse Pakistan</a><p>Your trusted destination for authentic gadgets, premium accessories and next-gen gaming gear. Genuine warranty, quick delivery and real support.</p></div><div><h2>Shop</h2><a href="{{ route('shop') }}">All products</a><a href="{{ route('shop', ['q' => 'audio']) }}">Audio & sound</a><a href="{{ route('shop', ['q' => 'gaming']) }}">Gaming gear</a></div><div><h2>Customer care</h2><a href="{{ route('cart') }}">Delivery & returns</a><a href="{{ route('cart') }}">Warranty information</a><a href="{{ route('cart') }}">Contact support</a></div><div><h2>We deliver nationwide</h2><p>Cash on delivery<br>Easypaisa & JazzCash<br>Official brand warranty</p></div></div><div class="page-width footer-bottom"><span>Copyright {{ date('Y') }} TechPulse Pakistan</span><span>Prices shown in Pakistani Rupees (PKR)</span></div></footer>
    <div class="toast" data-toast role="status" aria-live="polite"><span data-toast-message>Added to cart</span></div>
</body>
</html>